// Generated by CoffeeScript 1.9.3
(function() {
  var WebSocket;

  WebSocket = require("ws");

  module.exports = function(wss) {
    return {
      webSocket: function(ws, req) {
        return ws.on("message", function(msg) {
          console.log("Received:", msg);
          return wss.clients.forEach(function(client) {
            if (client.readyState === WebSocket.OPEN) {
              return client.send(msg);
            }
          });
        });
      },
      show: function(req, res) {
        return res.render("market/show.pug");
      }
    };
  };

}).call(this);
