// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    webSocket: function(ws, req) {
      ws.on("message", function(msg) {
        return console.log(msg);
      });
      return console.log(req.testing);
    },
    show: function(req, res) {
      return res.render("market/show.pug");
    }
  };

}).call(this);
