// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(Poll) {
    return {
      create: function(req, res) {
        var color, name, poll;
        poll = req.params.name;
        name = req.body.option;
        color = req.body.color;
        return Poll.findOne({
          name: poll
        }, function(err, poll) {
          var e;
          if (err) {
            req.flash("error", "Database error...");
            return res.redirect("/voting-app");
          }
          if (!poll) {
            req.flash("error", "The poll `" + poll.name + "` doesn't exist");
            return res.redirect("/voting-app");
          }
          if (!name) {
            req.flash("error", "Options need to be named");
            return res.redirect("/voting-app/poll/" + poll.name);
          }
          try {
            poll.addOption({
              description: name,
              color: color
            }, req.user);
            return poll.save(function() {
              return res.redirect("/voting-app/poll/" + poll.name);
            });
          } catch (_error) {
            e = _error;
            req.flash("error", e.message);
            return res.redirect("/voting-app/poll/" + poll.name);
          }
        });
      }
    };
  };

}).call(this);
