// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(db) {
    var Poll;
    Poll = require("./poll.js")(db);
    return {
      show: function(req, res) {
        return Poll.findOne({
          name: req.params.name
        }, function(err, poll) {
          return req.render("show_poll.pug", {
            poll: poll,
            user: req.user
          });
        });
      },
      create: function(req, res) {
        var description, name, options, poll, ref;
        ref = req.body, name = ref.name, description = ref.description, options = ref.options;
        poll = new Poll(req.user.name, name, description, options);
        return poll.save(function(err, poll) {
          if (err) {
            return req.redirect("/voting-app/polls/new");
          }
          return req.redirect("/voting-app/poll/" + (encodeURIComponent(poll.name)));
        });
      },
      "new": function(req, res) {
        return req.render("new_poll.pug", {
          user: req.user
        });
      },
      edit: function(req, res) {
        return Poll.findOne({
          name: req.params.name
        }, function(err, poll) {
          return req.render("edit_poll.pug", {
            user: req.user,
            poll: poll
          });
        });
      },
      index: function(req, res) {
        return Poll.all(function(err, polls) {
          return req.render("index_polls.pug", {
            user: req.user,
            polls: polls
          });
        });
      },
      update: function(req, res) {
        return Poll.findOne({
          name: req.params.name
        }, function(err, poll) {
          return req.redirect("/voting-app/poll/" + (encodeURIComponent(poll.name)) + "/edit");
        });
      },
      destroy: function(req, res) {
        return Poll.findOne({
          name: req.params.name
        }, function(err, poll) {
          return poll["delete"]();
        });
      }
    };
  };

}).call(this);
