// Generated by CoffeeScript 1.9.3
(function() {
  var Router, router;

  Router = require("../router.js");

  router = new Router(function(path, method) {
    if (method !== "get" && method !== "post") {
      path += "?_method=" + method.toUpperCase();
    }
    return path;
  });

  module.exports = router;

}).call(this);
