// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(User) {
    return {
      show: function(req, res) {
        return res.render("venues/show.pug");
      },
      index: function(req, res) {
        return res.render("venues/index.pug");
      }
    };
  };

}).call(this);
