// Generated by CoffeeScript 1.9.3
(function() {
  var yelpAuthentication;

  yelpAuthentication = function(req, res, next) {
    return next();
  };

  module.exports = function(User) {
    return {
      before: [yelpAuthentication],
      show: function(req, res) {
        return res.render("venues/show.pug");
      },
      index: function(req, res) {
        return res.render("venues/index.pug");
      }
    };
  };

}).call(this);
