// Generated by CoffeeScript 1.9.3
(function() {
  var cache, fetchYelpData, https;

  cache = require("memory-cache");

  https = require("https");

  fetchYelpData = function(req, res) {};

  module.exports = function(User) {
    return {
      show: function(req, res) {
        return res.render("venues/show.pug");
      },
      index: function(req, res) {
        var i, latitude, len, location, longitude, param, params, ref, ref1, type, url, view;
        ref = req.query, type = ref.type, longitude = ref.longitude, latitude = ref.latitude, location = ref.location;
        view = "venues/index.pug";
        if (((longitude != null) && (latitude != null)) || (location != null)) {
          params = [];
          ref1 = ["longitude", "latitude", "location"];
          for (i = 0, len = ref1.length; i < len; i++) {
            param = ref1[i];
            if (req.query[param] != null) {
              params.push(param + "=" + req.query[param]);
            }
          }
          url = "https://api.yelp.com/v3/businesses/search";
          if (params.length > 0) {
            url += "?" + params.join("&");
          }
          return https.get(url, function(resp) {
            var rawData;
            rawData = "";
            resp.on("data", function(chunk) {
              return rawData += chunk;
            });
            resp.on("end", function() {
              var e, parsedData;
              try {
                parsedData = JSON.parse(rawData);
                if (type === "json") {
                  return res.json(parsedData);
                } else {
                  return res.render(view, {
                    yelpData: parsedData
                  });
                }
              } catch (_error) {
                e = _error;
                if (type === "json") {
                  return res.status(500).json(e);
                } else {
                  if (Array.isArray(app.locals.flash["error"])) {
                    app.locals.flash["error"].push(e.message);
                  } else {
                    app.locals.flash["error"] = e.message;
                  }
                  return res.render(view);
                }
              }
            });
            return resp.on("error", function(err) {
              if (type === "json") {
                return res.status(500).json(err);
              } else {
                if (Array.isArray(app.locals.flash["error"])) {
                  app.locals.flash["error"].push(e.message);
                } else {
                  app.locals.flash["error"] = e.message;
                }
                return res.render(view);
              }
            });
          });
        } else {
          if ("json" === type) {
            return res.json({});
          } else {
            return res.render(view);
          }
        }
      }
    };
  };

}).call(this);
