// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(User) {
    var authentication;
    authentication = require("../authentication.js");
    return {
      before: function(req, res, next) {
        console.log("called");
        if (req.user) {
          return next();
        } else {
          return res.status(403).json({
            error: "You need to be authenticated to access this page"
          });
        }
      },
      update: function(req, res) {
        var id;
        id = req.params.venues_id;
        req.user.visit = id;
        return req.user.save(function() {
          return User.aggregateVisits([id]).then(function(visits) {
            return res.json({
              visits: visits[id]
            });
          });
        });
      },
      destroy: function(req, res) {
        var id;
        id = req.params.venues_id;
        req.user.visit = null;
        return req.user.save(function() {
          return User.aggregateVisits([id]).then(function(visits) {
            return res.json({
              visits: visits[id]
            });
          });
        });
      }
    };
  };

}).call(this);
