// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(User) {
    var authentication;
    authentication = require("../authentication.js");
    return {
      before: authentication.isAuthenticated,
      update: function(req, res) {
        var id;
        id = req.params.venues_id;
        req.user.visit = id;
        return req.user.save(function() {
          return User.aggregateVisits([id]).then(function(visits) {
            return res.json({
              url: res.locals.path.destroy_visits(id, "self"),
              visits: visits
            });
          });
        });
      },
      destroy: function(req, res) {
        var id;
        id = req.params.venues_id;
        req.user.visit = null;
        return req.user.save(function() {
          return User.aggregateVisits([id]).then(function(visits) {
            return res.json({
              url: res.locals.path.update_visits(id, "self"),
              visits: visits
            });
          });
        });
      }
    };
  };

}).call(this);
