// Generated by CoffeeScript 1.9.3
(function() {
  var instanciateUser;

  instanciateUser = function(db) {
    var User;
    return User = (function() {
      function User() {
        this.name = "";
        this.votes = [];
        this.id = null;
      }

      User.prototype.isAuthenticated = function() {
        return false;
      };

      User.prototype.save = function() {
        return db.save();
      };

      return User;

    })();
  };

  module.exports = instanciateUser;

}).call(this);
